# Generated by Django 4.0.6 on 2022-08-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersdetails',
            name='linkedInLink',
            field=models.URLField(default='x'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachersdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
