# Generated by Django 4.0.6 on 2022-08-22 12:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('course_duration', models.CharField(max_length=10)),
                ('suitable_for', models.CharField(max_length=100)),
                ('course_objective', models.TextField()),
                ('prerequisite', models.CharField(max_length=100)),
                ('course_fee', models.CharField(max_length=35)),
                ('course_content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursesVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
