# Generated by Django 4.0.6 on 2022-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesdetails',
            name='Fee_structure',
            field=models.CharField(default='x', max_length=150),
            preserve_default=False,
        ),
    ]
