# Generated by Django 4.0.6 on 2022-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_coursesdetails_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesvarity',
            name='url',
            field=models.CharField(default='x', max_length=18),
            preserve_default=False,
        ),
    ]
