# Generated by Django 4.0.6 on 2022-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_coursesvarity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesvarity',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
